package fbox;

import java.awt.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import java.sql.*;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author ukunc
 */
public class Start extends javax.swing.JFrame {

    private boolean statusPasswordInput = false;

    /**
     * Creates new form start_GUI
     */
    int userID;

    public Start(int userID) {
        this.userID = userID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        iconClose = new javax.swing.JPanel();
        icClose = new javax.swing.JLabel();
        iconMax = new javax.swing.JPanel();
        icMax = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tf_email = new javax.swing.JTextField();
        lb_judul = new javax.swing.JLabel();
        bt_log = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();
        LB_Barcode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(0, 0, 0));
        header.setPreferredSize(new java.awt.Dimension(800, 50));

        iconClose.setBackground(new java.awt.Color(0, 0, 0));
        iconClose.setPreferredSize(new java.awt.Dimension(50, 50));
        iconClose.setLayout(new java.awt.BorderLayout());

        icClose.setBackground(new java.awt.Color(51, 102, 255));
        icClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_32px.png"))); // NOI18N
        icClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icCloseMouseExited(evt);
            }
        });
        iconClose.add(icClose, java.awt.BorderLayout.CENTER);

        iconMax.setBackground(new java.awt.Color(0, 0, 0));
        iconMax.setPreferredSize(new java.awt.Dimension(50, 50));
        iconMax.setLayout(new java.awt.BorderLayout());

        icMax.setBackground(new java.awt.Color(51, 102, 255));
        icMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/full_screen_32px.png"))); // NOI18N
        icMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icMaxMouseExited(evt);
            }
        });
        iconMax.add(icMax, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Circular Std Black", 0, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PHOMORIA21.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Circular Std Black", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phomoria");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        dashboard.setBackground(new java.awt.Color(255, 255, 255));
        dashboard.setPreferredSize(new java.awt.Dimension(800, 400));
        dashboard.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 249, 249));

        tf_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        tf_email.setPreferredSize(new java.awt.Dimension(10, 20));
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        lb_judul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_judul.setText("Login Phomoria");

        bt_log.setBackground(new java.awt.Color(0, 0, 0));
        bt_log.setForeground(new java.awt.Color(255, 255, 255));
        bt_log.setText("Enter");
        bt_log.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 51, 255))); // NOI18N
        bt_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_logMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_logMouseExited(evt);
            }
        });
        bt_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Circular Std Black", 1, 18)); // NOI18N
        jLabel5.setText("Password :");

        jLabel6.setFont(new java.awt.Font("Circular Std Black", 1, 18)); // NOI18N
        jLabel6.setText("Email :");

        tf_pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));

        LB_Barcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Barcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/p logo.jpg"))); // NOI18N
        LB_Barcode.setToolTipText("");
        LB_Barcode.setMaximumSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf_pass)
                    .addComponent(bt_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LB_Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lb_judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Barcode, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_log, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        dashboard.add(jPanel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1204, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);

    }
    private void icCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icCloseMouseClicked

        if (!statusPasswordInput) {
            // Jika statusPasswordInput false, tampilkan input password
            showPasswordClose();

        }
    }//GEN-LAST:event_icCloseMouseClicked

    private void icCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icCloseMouseEntered
        changeColor(iconClose, new Color(240, 240, 240));
    }//GEN-LAST:event_icCloseMouseEntered

    private void icCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icCloseMouseExited
        changeColor(iconClose, new Color(0, 0, 0));
    }//GEN-LAST:event_icCloseMouseExited

    private void icMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icMaxMouseClicked
        if (!statusPasswordInput) {
            // Jika statusPasswordInput false, tampilkan input password
            showPasswordInput();
        }
    }//GEN-LAST:event_icMaxMouseClicked

    private void icMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icMaxMouseEntered
        changeColor(iconMax, new Color(240, 240, 240));
    }//GEN-LAST:event_icMaxMouseEntered

    private void icMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icMaxMouseExited
        changeColor(iconMax, new Color(0, 0, 0));
    }//GEN-LAST:event_icMaxMouseExited

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void bt_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_logMouseClicked

    private void bt_logMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logMouseEntered
        //        changeColor(bt_vc,new Color(240, 240, 240));
    }//GEN-LAST:event_bt_logMouseEntered

    private void bt_logMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_logMouseExited

    private void bt_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logActionPerformed
        String username = tf_email.getText();
        String plainPassword = tf_pass.getText();

        try {
            // Buat objek MessageDigest dengan algoritma MD5
            MessageDigest md = MessageDigest.getInstance("MD5");

            // Ubah kata sandi yang dimasukkan menjadi byte array
            byte[] passwordBytes = plainPassword.getBytes();

            // Hitung hash MD5 dari byte array kata sandi
            byte[] passwordHashBytes = md.digest(passwordBytes);

            // Ubah byte array hash MD5 menjadi format string hexadecimal
            StringBuilder sb = new StringBuilder();
            for (byte b : passwordHashBytes) {
                sb.append(String.format("%02x", b));
            }

            // Dapatkan kata sandi dalam format MD5
            String passwordMD5 = sb.toString();

            // Dapatkan ID pengguna dari database menggunakan metode getUserID
            int userID = getUserID(username, passwordMD5);

            if (userID != -1) {
//                System.out.println("user= "+userID);
                // Jika data pengguna ditemukan, buka jendela main_GUI dengan userID
                dispose();
                Dashboard mainpage = new Dashboard(userID);
                mainpage.show();
            } else {
                JOptionPane.showMessageDialog(this, "Email atau password tidak terdaftar");
                lb_judul.setText(plainPassword); // Ini hanya untuk debug, Anda dapat menghapusnya
                tf_email.setText("");
                tf_pass.setText("");
            }
        } catch (HeadlessException | NoSuchAlgorithmException e) {
        }
    }//GEN-LAST:event_bt_logActionPerformed
    private void showPasswordInput() {
        // Membuat JTextField untuk memasukkan password
        JPasswordField passwordField = new JPasswordField(20);

        // Membuat panel untuk menampilkan JTextField
        JPanel passwordPanel = new JPanel();
        passwordPanel.add(new JLabel("Masukkan password:"));
        passwordPanel.add(passwordField);

        // Menampilkan panel dan meminta input password
        int result = JOptionPane.showConfirmDialog(null, passwordPanel, "Konfirmasi Password", JOptionPane.OK_CANCEL_OPTION);
        statusPasswordInput = true; // Set statusPasswordInput menjadi true ketika password input aktif

        if (result == JOptionPane.OK_OPTION) {
            // Gantilah "passwordAnda" dengan password yang benar
            String passwordBenar = "admin";
            char[] inputPassword = passwordField.getPassword();

            // Periksa apakah password yang dimasukkan benar
            if (new String(inputPassword).equals(passwordBenar)) {
                // Jika password benar, ubah ukuran jendela
                if (getExtendedState() != fbox.Start.MAXIMIZED_BOTH) {
                    setExtendedState(Start.MAXIMIZED_BOTH);
                } else {
                    setExtendedState(Start.NORMAL);
                }
                statusPasswordInput = false;
            } else {
                // Jika password salah, tampilkan pesan kesalahan
                JOptionPane.showMessageDialog(null, "Password salah!", "Error", JOptionPane.ERROR_MESSAGE);
                statusPasswordInput = false;
            }
        } else if (result == JOptionPane.CANCEL_OPTION) {
            statusPasswordInput = false; // Atur statusPasswordInput menjadi false
            // Tutup dialog
        }
    }

    private void showPasswordClose() {
        // Membuat JTextField untuk memasukkan password
        JPasswordField passwordField = new JPasswordField(20);

        // Membuat panel untuk menampilkan JTextField
        JPanel passwordPanel = new JPanel();
        passwordPanel.add(new JLabel("Masukkan password:"));
        passwordPanel.add(passwordField);

        // Menampilkan panel dan meminta input password
        int result = JOptionPane.showConfirmDialog(null, passwordPanel, "Konfirmasi Password", JOptionPane.OK_CANCEL_OPTION);
        statusPasswordInput = true; // Set statusPasswordInput menjadi true ketika password input aktif

        if (result == JOptionPane.OK_OPTION) {
            // Gantilah "passwordAnda" dengan password yang benar
            String passwordBenar = "admin";
            char[] inputPassword = passwordField.getPassword();

            // Periksa apakah password yang dimasukkan benar
            if (new String(inputPassword).equals(passwordBenar)) {
                // Jika password benar, ubah ukuran jendela

                statusPasswordInput = false;
                System.exit(0);
            } else {
                // Jika password salah, tampilkan pesan kesalahan
                JOptionPane.showMessageDialog(null, "Password salah!", "Error", JOptionPane.ERROR_MESSAGE);
                statusPasswordInput = false;
            }
        } else if (result == JOptionPane.CANCEL_OPTION) {
            statusPasswordInput = false; // Atur statusPasswordInput menjadi false
            // Tutup dialog
        }
    }

    public int getUserID(String username, String password) {
//        int userID = -1; // Nilai default jika data tidak ditemukan

        try (Connection con = koneksi.ConfigDB.conect()) {
            Statement stm = con.createStatement();
            String sql = "SELECT * FROM users WHERE email='" + username + "' AND password='" + password + "'";
            ResultSet rs = stm.executeQuery(sql);

            // Jika data ditemukan, isi userID dengan nilai dari database
            if (rs.next()) {
                userID = rs.getInt("id_users");
            }

        } catch (SQLException e) {
        }

        return userID;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            new Start(0).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Barcode;
    private javax.swing.JButton bt_log;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel header;
    private javax.swing.JLabel icClose;
    private javax.swing.JLabel icMax;
    private javax.swing.JPanel iconClose;
    private javax.swing.JPanel iconMax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_judul;
    private javax.swing.JTextField tf_email;
    private javax.swing.JPasswordField tf_pass;
    // End of variables declaration//GEN-END:variables
}
